name: aws ecr 
on:
  push:
    branches:
      - main

jobs:
  aws_ecr_push:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: login ecr 
        env:
          ECR_REGISTRY: 654654507153.dkr.ecr.us-east-1.amazonaws.com
          ECR_REPOSITORY: ashish
          IMAGE_TAG: ashish-${{ github.run_id }}
          
        run: |
         aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 654654507153.dkr.ecr.us-east-1.amazonaws.com $ECR_REGISTRY

      - name : pull image in docker hub
        run : |
        
         sudo docker tag ashish:latest /ashish:latest

      - name : push on ecr 
        run: | 
         sudo docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
