name: aws ecr 
on:
  push:
    branches:
      - rohit
  
jobs:
  aws_ecr_push:
    runs-on: self-hosted
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: login ecr 
        env:
        
          IMAGE_TAG: ${{ github.run_id }}
        run: |
         aws ecr get-login-password --region us-east-1 | sudo docker login --username AWS --password-stdin $ECR_REGISTRY

      - name : pull image in docker hub 
        run : |
         sudo docker pull nginx:latest
         sudo docker tag nginx:$IMAGE_TAG

      - name : push on ecr 
        run: | 
         sudo docker push:$IMAGE_TAG
